import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys

# Create output directories if they don't exist
os.makedirs("assets", exist_ok=True)

# 1. Academic Styling
sns.set_theme(style="ticks", context="paper", font_scale=1.3)
plt.rcParams['font.family'] = 'serif'
plt.rcParams['figure.dpi'] = 300
plt.rcParams['savefig.dpi'] = 300

def generate_physics_plot(delta_k, da_dn_theoretical, da_dn_model):
    plt.figure(figsize=(7.5, 5.5))
    
    # Plot the TRUE theoretical physics law (straight line on log-log)
    plt.loglog(delta_k, da_dn_theoretical, 'k-', linewidth=2.5, label=r"Theoretical Paris Law ($m=3.0$)")
    
    # Plot YOUR model's actual learned latent representation
    # Using scatter to show the deterministic spread/failure
    plt.loglog(delta_k, da_dn_model, 'o', color='#d62728', markersize=5, alpha=0.7, label="ThermoPINN Latent Dynamics")
    
    # Formatting
    plt.title("Latent Space Divergence from Empirical Physics", fontweight='bold', pad=15)
    plt.xlabel(r"Stress Intensity Factor Range ($\Delta K$)", fontweight='bold')
    plt.ylabel(r"Crack Growth Rate ($da/dN$)", fontweight='bold')
    
    plt.legend(loc='upper left', frameon=True, edgecolor='black')
    
    # Both axes log scale needs a distinct grid
    plt.grid(True, which="major", linestyle='-', alpha=0.3)
    plt.grid(True, which="minor", linestyle=':', alpha=0.2)
    
    sns.despine(trim=False)
    plt.tight_layout()
    
    # Save
    save_path = "assets/fig2_physics_violation.png"
    plt.savefig(save_path, bbox_inches='tight')
    print(f"Success! 100% Real Physics Violation plot saved to {save_path}")

if __name__ == "__main__":
    # ==========================================
    # LOAD YOUR REAL PHYSICS DATA HERE
    # ==========================================
    # Update this path to wherever your physics validation script saved its outputs
    csv_path = "data/paris_law_validation_results.csv" 
    
    if not os.path.exists(csv_path):
        print(f"🛑 ERROR: Could not find {csv_path}.")
        print("To make this 100% real, you must point this script to the actual CSV generated by your physics evaluation script.")
        sys.exit(1)
        
    # Load your real data
    df = pd.read_csv(csv_path)
    
    # Extract the exact columns (Update these column names if yours are different!)
    # To get a clean plot, you might need to sort the values by delta_k first
    df = df.sort_values(by='delta_k')
    
    real_delta_k = df['delta_k'].values
    real_da_dn_theo = df['true_crack_growth'].values
    real_da_dn_model = df['predicted_latent_growth'].values
    
    # Generate the unquestionable proof
    generate_physics_plot(real_delta_k, real_da_dn_theo, real_da_dn_model)